### ISSUE TITLE
QR Code Optimization

### ISSUE THREAD

**Issue by theofandrich** [harmony-one/HarmonyOneBot#26]
1. Make prompt part of the photo reply as a caption.
2. Implement solution to improve QR code generation quality.

![IMAGE 2023-07-15 15:36:22](https://github.com/harmony-one/HarmonyOneBot/assets/139378766/0ad2edb6-a6bf-4687-baef-44649e9ffd54)

**Comment by ahiipsa** [comment]
> Make prompt part of the photo reply as a caption.

[Done](https://github.com/harmony-one/HarmonyOneBot/pull/31/files#diff-b5e21823e003508a76ca26c20adf9f0ecc80ee74a38ae274dc0c279ea336df52R187)

<img width="471" alt="image" src="https://github.com/harmony-one/HarmonyOneBot/assets/1662798/13587a71-ace4-4e91-8a95-7570e880f1aa">
>
